### ISSUE TITLE
During build the whole directory gets copied to target

### ISSUE THREAD

**Issue by rudolfson** [michaeldejong/EveNexus#1]
When doing a build with mvn install the whole working directory (including src and target) gets copied to the target directory. Is this on purpose?

**Comment by michaeldejong** [comment]
Yeah this does indeed not sound like a very good idea. I'll have a look tonight (or did you find a solution already?)

**Comment by rudolfson** [comment]
I removed the whole plugin (maven-resources-plugin) from the pom.xml . Build seems to work. I already pushed the changes into my fork.

**Comment by rudolfson** [comment]
Oops, pressed close by accident.

**Comment by rudolfson** [comment]
You pulled the changes into your repo - so I'll close this one.
