### ISSUE TITLE
"null" in window title

### ISSUE THREAD

**Issue by rudolfson** [michaeldejong/EveNexus#10]
The window title currently read "null - EVE Online trading overview". I found the following line setting the title

```setTitle(getClass().getPackage().getSpecificationTitle() + " - EVE Online trading overview");

```
Is the specification written into the manifest file on packaging?
```

**Comment by michaeldejong** [comment]
Yes this is indeed done during packaging. The same applies to the version number of EveNexus.

**Comment by rudolfson** [comment]
Thanks. I'll close the issue then.
