### ISSUE TITLE
Reloading tables

### ISSUE THREAD

**Issue by michaeldejong** [michaeldejong/EveNexus#11]
Tables do not seem to be reloading properly when their data has changed. Investigate this. Most likely cause is that the importers are not notifying the (right) panels of new data.

**Comment by rudolfson** [comment]
Yep, at the moment for journal and transactions switching the timeframe does update the table correctly. With profits its worse. Seems like the data is cached and new transactions don't trigger a reload of the underlying data. In the profits table switching timeframes doesn't seem to help. I had to restart the application.

**Comment by michaeldejong** [comment]
Dashboard is still not reloading properly. When starting without a database, adding a few characters should trigger a reload of the dashboard tab, but it does not do that.

**Comment by michaeldejong** [comment]
This should be fixed as of the 0.1.14 release of EveNexus
