### ISSUE TITLE
save buy price and sell price in profit table

### ISSUE THREAD

**Issue by rudolfson** [michaeldejong/EveNexus#3]
By saving the sell price and buy price in the profit table it is possible to calculate all other values like
- profit per item
- total profit
- profit in percent

This also open opportunities for a wide variety in later reports.

**Comment by rudolfson** [comment]
I'll work on this. Problem is achieving compatibility with former databases. Would it be possible to recalculate the profits from stored transactions? (BTW this could be a handy feature if anything goes wrong).

**Comment by michaeldejong** [comment]
This is basically already possible. Every Profit entity is a match between a buy and a sell order. (See the ProfitIdentifier). You should be able to query the buy and sell price from there. I'd avoid redundant ref fields as much as possible.

**Comment by rudolfson** [comment]
But the current database (the version which is available on the website) doesn't have the buy and sell order reference - or did i just overlook something?

Becuse the profit entries do have references to both (in the new version), we could avoid redundancy completely. The question is how the performance would be. What do you think - should we remove prices completely from the profit entity and join / calculate on demand?

**Comment by michaeldejong** [comment]
Indeed, I was talking about the newer version. Hmmm, this makes my think... Basically all we really need in the profit entity, is a reference to the buy and sell order, and the quantity (amount of items) associated with the match, right? This is all the information we required to calculate the actual profit / taxes / etc. at a later date. 

We could see how fast this works in the database (H2 is pretty fast, especially with some nice indices). This would make the profit calculation process not only faster, but also more simple. Tempting, this is definately worth investigating.

**Comment by rudolfson** [comment]
Hmmm, and for easier use and mapping we could define a view for the profits with all calculated values and then map this view as a read-only entity.

**Comment by michaeldejong** [comment]
Excellent idea! :D. Profits are generally read-only anyway, and this also avoids us having to write complicated joins. Nice one. Do you want to pick this up? or would you like me to do it?

**Comment by rudolfson** [comment]
I would like to do it. Backend suits me better. :-)

**Comment by rudolfson** [comment]
Committed refactoring of profits:
- former Profit (matching buy and sell order) is now MatchinTransaction (table matching_transactions)
- new view profits containing all profit data - mapped to class Profit
- adapted StructureUpgrader accordingly

I didn't add a drop for the profit table yet. Am I right that if I delete profit table, it will be recreated? To me the upgrading from a previous database is still unclear.

(Edit: I gotta learn distinguishing those two buttons. ;-))

**Comment by rudolfson** [comment]
One thing I recognized: When comparing the profits in the released version 0.1.13 and the dev version I see that in the released one some profits are aggregated. Am I right this doesn't work for the new profits due to the fact, that each profit entry  refers to exactly one buy and one sell transaction or did I just messed up something in the code?

**Comment by michaeldejong** [comment]
Not really sure what you mean, but the development version does have a newer system to match transactions. Btw, I noticed two unit tests are failing, although I haven't checked out yet, why. Did you run the test suite before committing?

**Comment by rudolfson** [comment]
Oops, will test it - tomorrow.

**Comment by rudolfson** [comment]
Testing with maven didn't reveal any errors. Testing in Eclipse showed error in RevisionCollectionTest.testRegisterNullValue(). This was due to the fact, that assertions weren't active in the run configuration. I replaced the assert with a call to Preconditions.checkArgument().

Where did you get errors?

**Comment by michaeldejong** [comment]
I've got a build server running which polls GitHub for changes every 5 minutes. You can check the results of unit tests there: http://141.138.193.49:8080/jenkins/job/EveNexus%20CI/. If you want I could also add such a build to your own repository on GitHub.

It seems like the following tests are failing:
nl.minicom.evenexus.inventory.InventoryWorkerTest.testMixedTransactions
nl.minicom.evenexus.inventory.InventoryWorkerTest.testInvalidlyOrderedTransactions

**Comment by rudolfson** [comment]
Hmm, those aren't failing locally. Would be nice if you setup a job for my repository. I already had a look at your Jenkins installation. We used Hudson (the previous version, before Oracle came) at work. Good thing to have! :)

**Comment by rudolfson** [comment]
Thanks for setting up jenkins. There seems to be a problem with the git configuration - could you please have a look into this problem?

**Comment by michaeldejong** [comment]
yeah I've been looking into it. It seems the maven-buildnumber-plugin is the problem. I'll try again tonight.

**Comment by rudolfson** [comment]
Did you change anything yet? Last build worked.

**Comment by michaeldejong** [comment]
Seems like it fixed itself. Last night, I committed a change in the POM file. I disabled some checks of the buildnumber plugin. When you pulled my repo you got that change, and when you pushed your changes to your own repo, Jenkins was triggered and the build succeeded! The only thing I still have to do is re-enable the jenkins mailer.
