### ISSUE TITLE
API Proxy in Settings seems to be ignored on startup

### ISSUE THREAD

**Issue by rudolfson** [michaeldejong/EveNexus#8]
When changing the api proxy in the settings tab and exiting the application, the proxy setting is saved to the session.properties. After starting the application again, the api proxy is resetted in the settings panel.

**Comment by michaeldejong** [comment]
It appears that the settings are not loaded in properly on startup. I'll fix this one.

**Comment by michaeldejong** [comment]
This has been fixed. Everything should again work as intended.
