### ISSUE TITLE
Display percental profits

### ISSUE THREAD

**Issue by rudolfson** [michaeldejong/EveNexus#9]
Add columns for percental profits (gross + net).

**Comment by rudolfson** [comment]
Implemented in commit 50773f4623dd09b577a5

**Comment by michaeldejong** [comment]
Something's not right. I tested this by buying 100 tritanium @ 3,56 ISK a piece. I sold 30 units of tritanium @ 3,36 ISK a piece. The profits panel marks this transaction as a loss, but the percentages are green (and positive). "Percental profit (exc. taxes)" marks a 5.62% profit, while "Percental profit (inc. taxes)" marks a 7.02% profit. Could you perhaps have added a minus somewhere? Note that buy transactions are stored with a negative price, while sell transactions have a positive price.

**Comment by rudolfson** [comment]
I'll have a look.

**Comment by rudolfson** [comment]
If you look at [StructureUpgrader Line 766/767](https://github.com/michaeldejong/EveNexus/blob/master/src/main/java/nl/minicom/evenexus/persistence/versioning/StructureUpgrader.java#L766) I do multiply by -100 due to the fact I'm dividing by the buy price, which is negative. So if you check those calculations manually they should always bring the right result. You could also use multiply by 100 and use  ABS(b.price), this would methematically be the same.

Sure you ran it with the latest version?
If so, did you use a clean database?
Maby there are problems with the transactions stored in the database?

**Comment by michaeldejong** [comment]
I suspect this might not be a clean database (thought I removed the old one). When I get back from work, I'll try it with a new database. But I think the "Percental profit (inc. taxes)" is still wrong. Should that column not always show a lower value than "Percental profit (exc. taxes)"? I'll have a more indepth look at home.

**Comment by rudolfson** [comment]
It should, yes. And it does when I test it.

**Comment by michaeldejong** [comment]
Ok then it's probably the older version of the profit view. I'll let you know as soon as I double checked it at home :)

**Comment by michaeldejong** [comment]
Yup works when using a newer database.
